version: '3.3'
services:
  json_server:
    container_name: json_server
    restart: always
    image: curso-practica:v3
    hostname: json_server
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
          VERSION_ARG: 19
          PORT_ARG: 3000
    ports:
      - "8085:3000"
    networks:
      - network
    volumes:
      - ./:/app
    
volumes:
  json_server_data:
networks:
  network:
    external: true
